<div>
    <div id="contentLeft_OhneInfobox">
        <div id="contentTextSpalteLinks_OhneInfobox">
            <h3>Der BusinessExcellence Check 2011</h3>
        </div>
    </div>
    <div id="contentRight_OhneInfobox">
        <div id="contentTextSpalteRechts_OhneInfobox"></div>
    </div>
</div>
<p class="clearFloat"></p>
<div id="contentWrapper">
    <!-- Beitrag beginnt hier -->


    <p class="clearFloat"></p>
    <?php echo $this->form; ?>


    <br />
    <br />

</div>

<?php if (isset($this->result)) : ?>
        <script type="text/javascript">
            $(function() {
                $('#be-result').fadeIn('normal');
                $('#be-result-close').click(function(){
                    $('#be-result').fadeOut('normal', function() {
                        $('#be-overlay').fadeOut('normal');
                    });

                    return false;
                });
            })
        </script>
        <div id="be-overlay"></div>
            <div id="be-result">
                <div id="be-result-close" style="text-align: right;" >SCHLIESSEN</div>
                <h1>BE-CHECK 2011</h1>
                <p>ergibt für Sie <?php echo $this->result; ?> % von 100 % an exzellenten Ansätzen</p>
                <p><span>Ihr Unternehmen befindet sich hier:</span></p>

                <div id="be-result-bar">
                    <!-- width:30px ist 0% -- width:766px ist 100% -->
                    <div id="be-result-arrow" style="width:<?php echo round($this->result * 7.36 + 30); ?>px"><img src="../pics/be-arrow.png" alt="" title="<?php echo round($this->result * 7.36 + 30); ?>" width="30" height="30" /></div>
                </div>

                <div id="be-result-text">
                    <p>
                <?php if ($this->result <= 30) : ?>
                    Ihr Unternehmen scheint auf dem besten Weg zur Exzellenz zu sein. Sollte sich
                    bei einem BE-Audit vor Ort dieser Eindruck bestätigen, fehlen Ihrem
                    Unternehmen nur mehr Nuancen zur Exzellenz, wenn es nicht schon exzellent
                    ist. Damit es nachhaltig gut bleibt, müssen die richtigen Weichen für die
                    Zukunft gestellt werden. Finden wir gemeinsam heraus, ob und wie wir Sie
                    unterstützen können.
                <?php elseif ($this->result <= 65): ?>
                        Ihr Unternehmen scheint hinsichtlich Strategie, Prozesse und Personal und der
                        Orientierung bezüglich aller Firmeninteressensgruppen gut aufgestellt zu sein. Sie sind durchaus in Richtung Exzellenz unterwegs. Durch ein Gespräch, eine Firmenbesichtigung oder ein etwas umfangreicheres BE-Audit lässt sich
                        ermitteln, wo Ihr Unternehmen Verbesserungspotenziale hat und ob und wie wir Ihnen helfen können.
                <?php elseif ($this->result <= 91) : ?>
                            Ihr Unternehmen verfügt offensichtlich über grundlegende Mechanismen zu
                            Strategie, Prozessen und Personal, weist jedoch anscheinend einige
                            Verbesserungspotenziale auf. Wo diese genau verborgen sind und wie diese
                            Potenziale für die Zukunft genutzt werden können, sollte in einem Gespräch,
                            einem Firmenbesuch oder eventuell in einem BE-Audit geklärt werden. Daraus
                            lässt sich ableiten, was wir für Sie tun können.
                <?php else : ?>
                                Zwar verfügt Ihr Unternehmen anscheinend über die ein oder anderen Stärken
                                bezüglich Strategie, Prozesse oder Personal. Für die Ausrichtung in Richtung
                                unternehmerische Exzellenz scheint jedoch noch Bedarf zu bestehen. Dies lässt
                                sich durch ein gemeinsames Gespräch klären, in dem Möglichkeiten zu kurzund
                                mittelfristigen Maßnahmenableitung erörtert werden können.
                <?php endif; ?>
                            </p>

                        </div>
                    </div>

<?php endif; ?>