<div>
    <div id="contentLeft_OhneInfobox">
        <div id="contentTextSpalteLinks_OhneInfobox">
            <h3>Der BusinessExcellence Check 2011</h3>
        </div>
    </div>
    <div id="contentRight_OhneInfobox">
        <div id="contentTextSpalteRechts_OhneInfobox"></div>
    </div>
</div>
<p class="clearFloat"></p>
<div id="contentWrapper">
    <!-- Beitrag beginnt hier -->


    <p class="clearFloat"></p>
   Vielen Dank. Wir werden uns in Kürze mit Ihnen in Verbindung setzen.


    <br />
    <br />

</div>
