  <h1>BE-CHECK 2011</h1>
  <p>ergibt für Sie 65 % von 100 % an exzellenten Ansätzen</p>
  <p><span>Ihr Unternehmen befindet sich hier:</span></p>

  <div id="be-result-bar">
    <!-- width:30px ist 0% -- width:766px ist 100% -->
    <div id="be-result-arrow" style="width:766px"><img src="../pics/be-arrow.png" alt="" width="30" height="30" /></div>
  </div>

  <div id="be-result-text">
    <p>Ihr Unternehmen scheint auf dem besten Weg zur Exzellenz zu sein. Sollte sich
    bei einem BE-Audit vor Ort dieser Eindruck bestätigen, fehlen Ihrem
    Unternehmen nur mehr Nuancen zur Exzellenz, wenn es nicht schon exzellent
    ist. Damit es nachhaltig gut bleibt, müssen die richtigen Weichen für die
    Zukunft gestellt werden. Finden wir gemeinsam heraus, ob und wie wir Sie
    unterstützen können.</p>

  </div>
