<div id="contentWrapper">
    <div id="contentLeft_OhneInfobox">
        <div id="contentTextSpalteLinks_OhneInfobox">
            <h3>Der BusinessExcellence Check 2011</h3>
        </div>
    </div>
    <div id="contentRight_OhneInfobox">
        <div id="contentTextSpalteRechts_OhneInfobox"></div>
    </div>
</div>
<p class="clearFloat"></p>

<div class="be-box1">
    <div class="be-left">CHECK 2011</div> Teil 2 von 2
</div>

<div class="be-box2">
    <span class="be-text1">Zutreffende Maßnahmen bitte anklicken&nbsp;&nbsp;&nbsp;</span>
    <span class="be-text2">Es können bis zu 3 Antworten pro Frage gewählt werden.</span>
</div>

<fieldset>
    <h3>Wie erfolgt in Ihrem Unternehmen die Entwicklung und Anpassung der Unternehmensstrategie?</h3>

    <div class="be-group">
        <label class="be-label">Unsere erfahrene Führungsmannschaft lebt unsere Strategie. Sie muss nicht explizit ausgedrückt oder umformuliert werden.</label>
        <label class="checkbox"><input type="checkbox" name="q3" id="q3" value="1" /></label>
    </div>

    <div class="be-group">
        <label class="be-label">Unser Know-how und unsere Partnerschaften mit Lieferanten fließen in unsere Strategie ein.</label>
        <label class="checkbox"><input type="checkbox" name="q3" id="q3" value="0" /></label>
    </div>

    <div class="be-group">
        <label class="be-label">Unsere Strategie hat sich über Jahre bewährt und muss nicht ständig angepasst werden.</label>
        <label class="checkbox"><input type="checkbox" name="q3" id="q3" value="0" /></label>
    </div>

    <div class="be-group">
        <label class="be-label">Unsere Strategie leitet sich ausschließlich von unseren Kernkompetenzen ab.</label>
        <label class="checkbox"><input type="checkbox" name="q3" id="q3" value="0" /></label>
    </div>

    <div class="be-group">
        <label class="be-label">Wir uberprufen unsere Strategie jährlich und machen viertel- bis halbjährlich ein kurzes Review.</label>
        <label class="checkbox"><input type="checkbox" name="q3" id="q3" value="1" /></label>
    </div>

    <div class="be-group">
        <label class="be-label">Politische und gesellschaftliche Änderungen sind Basis fur unsere Strategie.</label>
        <label class="checkbox"><input type="checkbox" name="q3" id="q3" value="1" /></label>
    </div>

</fieldset>

<div class="be-button">
    <input type="button" value="Auswertung" />
</div>



<h3>Freiwillige Angaben</h3>

<fieldset>
    <h3>Ihre Daten</h3>

    <label class="be-label">Name des Unternehmens</label><input type="text" /><br />
    <label class="be-label">Ihr Name</label><input type="text" /><br />
    <label class="be-label">Ihre mail-Adresse</label><input type="text" /><br />
    <label class="be-label">JA, bitte werten Sie meine Antworten individuell aus und nehmen Sie unverbindlich Kontakt zu mir auf.</label>
    <label class="checkbox"><input type="checkbox" name="q3" id="q3" value="0" /></label>
</fieldset>

<div class="be-button">
    <input type="button" value="Senden" />
</div>

