<div>
    <div id="contentLeft_OhneInfobox">
        <div id="contentTextSpalteLinks_OhneInfobox">
            <h3>Der BusinessExcellence Check 2011</h3>
        </div>
    </div>
    <div id="contentRight_OhneInfobox">
        <div id="contentTextSpalteRechts_OhneInfobox"></div>
    </div>
</div>
<p class="clearFloat"></p>
<div id="contentWrapper">
    <!-- Beitrag beginnt hier -->

    <div class="be-box1">
        <div class="be-left">CHECK 2011</div> Teil 1 von 2
    </div>

    <div class="be-box2">
        <div class="be-left">Ihr Unternehmen</div><span class="be-text1">Erfüllungsgrad in %&nbsp;&nbsp;&nbsp;</span>
        <span class="be-text2">Bitte klicken Sie einfach in das gewünschte Antwortfeld</span>
    </div>

    <div class="be-box3">
        <div class="left">Erfüllung in % oder NICHT verwendet, vorhanden, praktiziert.</div>
        <div class="right">Erfüllung in % oder DURCHGÄNGIG verwendet, vorhanden, praktiziert.</div>
    </div>

    <p class="clearFloat"></p>

    <div class="be-box4">
        <div><span>0-29%</span></div>
        <div><span>30-49%</span></div>
        <div><span>50-64%</span></div>
        <div><span>65-79%</span></div>
        <div><span>80-95%</span></div>
        <div><span>96-100%</span></div>
    </div>

    <p class="clearFloat"></p>
    <?php echo $this->form; ?>


    <br />
    <br />

</div>