<div>
    <div id="contentLeft_OhneInfobox">
        <div id="contentTextSpalteLinks_OhneInfobox">
            <h3>Der BusinessExcellence Check 2011</h3>
        </div>
    </div>
    <div id="contentRight_OhneInfobox">
        <div id="contentTextSpalteRechts_OhneInfobox"></div>
    </div>
</div>
<p class="clearFloat"></p>
<div id="contentWrapper">
    <!-- Beitrag beginnt hier -->

    <div class="be-box1">
        <div class="be-left">CHECK 2011</div> Teil 1 von 2
    </div>

    <div class="be-box2">
        <div class="be-left">Ihr Unternehmen</div><span class="be-text1">Erfüllungsgrad in %&nbsp;&nbsp;&nbsp;</span>
        <span class="be-text2">Bitte klicken Sie einfach in das gewünschte Antwortfeld</span>
    </div>

    <div class="be-box3">
        <div class="left">Erfüllung in % oder NICHT verwendet, vorhanden, praktiziert.</div>
        <div class="right">Erfüllung in % oder DURCHGÄNGIG verwendet, vorhanden, praktiziert.</div>
    </div>

    <p class="clearFloat"></p>

    <div class="be-box4">
        <div><span>0-29%</span></div>
        <div><span>30-49%</span></div>
        <div><span>50-64%</span></div>
        <div><span>65-79%</span></div>
        <div><span>80-95%</span></div>
        <div><span>96-100%</span></div>
    </div>

    <p class="clearFloat"></p>
    <?php echo $this->form; ?>


    <br />
    <br />

</div>
<script type="text/javascript">
    $(function() {
        $('#be-result-close').click(function(){
            $('#be-result').slideDown().hide('slow');
            return false;
        });
    })
</script>
<?php if(!isset($this->result)) : ?>
<div id="be-result">
  <div id="be-result-close" style="text-align: right;" >SCHLIESSEN</div>
  <h1>BE-CHECK 2011</h1>
  <p>ergibt für Sie 65 % von 100 % an exzellenten Ansätzen</p>
  <p><span>Ihr Unternehmen befindet sich hier:</span></p>

  <div id="be-result-bar">
    <!-- width:30px ist 0% -- width:766px ist 100% -->
    <div id="be-result-arrow" style="width:766px"><img src="../pics/be-arrow.png" alt="" width="30" height="30" /></div>
  </div>

  <div id="be-result-text">
    <p>Ihr Unternehmen scheint auf dem besten Weg zur Exzellenz zu sein. Sollte sich
    bei einem BE-Audit vor Ort dieser Eindruck bestätigen, fehlen Ihrem
    Unternehmen nur mehr Nuancen zur Exzellenz, wenn es nicht schon exzellent
    ist. Damit es nachhaltig gut bleibt, müssen die richtigen Weichen für die
    Zukunft gestellt werden. Finden wir gemeinsam heraus, ob und wie wir Sie
    unterstützen können.</p>

  </div>
</div>

<?php endif; ?>