<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
        <meta name="author" content="" />
        <meta name="date" content="2011-01-11" />
        <meta http-equiv="expires" content="0" />
        <meta http-equiv="content-language" content="com,de,at,ch" />
        <meta http-equiv="Pragma" content="no-cache" />

        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="imagetoolbar" content="false" />
        <meta name="revisit-after" content="1 days" />
        <meta name="robots" content="index,follow" />
        <meta name="description" content="Steinbeis Beratungszentrum, Business Excellence, Unternehmensberatung" />
        <meta name="keywords" content="Steinbeis Beratungszentrum, Business Excellence, Unternehmensberatung, Organisationsberatung, Innovationsmanagement, Personalberatung" />
        <link href="../css/style.css" rel="stylesheet" type="text/css" />
        <link href="../css/be_check.css" rel="stylesheet" type="text/css" />

        <script src="../js/jquery.js" type="text/javascript"></script>
        <script src="../js/jquery.custom_radio_checkbox.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                $(".radio").dgStyle();
                $(".checkbox").dgStyle();
            });
        </script>

    </head>
    <body>
        <div id="containerBE_Check">
            <div id="headerGrey">
                <div id="headerGreyLogo"><img src="../pics/stw_logo_header1.png" alt="stw " width="190" height="25" /></div>
                <div id="headerGreySuche"></div>
            </div>
            <div id="headerContent"></div>
            <div id="navigation">
                <div id="main_menu">
                    <ul id="nav">
                        <li class="active"><a href="/html/warum_beratung.html" onfocus="blurLink(this);">Warum Beratung?</a>
                            <ul class="menu2">
                                <li><a href="/html/wer_braucht_beratung.html" onfocus="blurLink(this);">Wer braucht Beratung</a></li>
                                <li><a href="/html/BE_Quick_Check.html" onfocus="blurLink(this);">BE Quick Check</a></li>
                            </ul>
                        </li>
                        <li><a href="/html/wir_ueber_uns.html" onfocus="blurLink(this);">Wir über uns</a>
                            <ul class="menu2">
                                <li><a href="/html/philosophie.html" onfocus="blurLink(this);">Philosophie</a></li>
                                <li><a href="/html/team.html" onfocus="blurLink(this);">Team</a></li>
                                <li><a href="/html/steinbeis.html" onfocus="blurLink(this);">Steinbeis</a></li>
                            </ul>
                        </li>
                        <li><a href="/html/business.html" onfocus="blurLink(this);">Business</a>
                            <ul class="menu2">
                                <li><a href="/html/strategie.html" onfocus="blurLink(this);">Strategie</a></li>
                                <li><a href="/html/prozessmanagement.html" onfocus="blurLink(this);">Prozess-<br />management</a></li>
                                <li><a href="/html/marketingmanagement.html" onfocus="blurLink(this);">Marketing-<br />management</a></li>
                            </ul>
                        </li>
                        <li><a href="/html/innovation.html" onfocus="blurLink(this);">Innovation</a>
                            <ul class="menu2">
                                <li><a href="/html/diversifikation.html" onfocus="blurLink(this);">Diversifikation</a></li>
                                <li><a href="/html/produkt-marktentwicklung.html" onfocus="blurLink(this);">Produkt- und<br />Marktentwicklung</a></li>
                                <li><a href="/html/changemanagement.html" onfocus="blurLink(this);">Change<br />Management</a></li>
                            </ul>
                        </li>
                        <li><a href="/html/personal.html" onfocus="blurLink(this);">Personal</a>
                            <ul class="menu2">
                                <li><a href="/html/recruiting.html" onfocus="blurLink(this);">Recruiting</a></li>
                                <li><a href="/html/personalentwicklung.html" onfocus="blurLink(this);">Personal-<br />entwicklung</a></li>
                                <li><a href="/html/organisationsentwicklung.html" onfocus="blurLink(this);">Organisations-<br />entwicklung</a></li>
                                <li><a href="/html/mitarbeiterbindung.html" onfocus="blurLink(this);">Mitarbeiter-<br />bindung</a></li>
                            </ul>
                        </li>
                        <li><a href="/kontakt.html" onfocus="blurLink(this);">Kontakt</a></li>
                    </ul>
                </div>
            </div>
            <div id="contentBereich">
                <div id="breadcrumb">
                    <ul id="breadcrumbListe">
                        <li><a href="/index_.html">Startseite </a>&raquo;</li>
                        <li><a href="/html/warum_beratung.html">Warum Beratung? </a>&raquo;</li>
                        
                        <li>BE Quick Check </li>
                    </ul>
                </div>
                <div id="contentText">
                     <?php echo $this->layout()->content; ?>
                    <p class="clearFloat" />
                </div>
                <br />
                <br />
                <div id="contentFooter"></div>
                <div id="metaNavigation"><a href="/html/impressum.html">Impressum</a></div>
            </div>
        </div>

    </body>
</html>


